# Generated by Django 5.0.2 on 2024-03-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('brithday', models.DateTimeField()),
                ('profile_photo', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('vip', models.BooleanField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('frequency_purchase', models.BigIntegerField()),
                ('notify', models.BooleanField()),
                ('frequency_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.usermanagement')),
            ],
        ),
    ]
