# Generated by Django 5.0.2 on 2024-03-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='brithday',
            new_name='birthday',
        ),
    ]
